#file: noinspection SpringBootApplicationYaml
spring:
  datasource:
    password: springstudent
    url: jdbc:mysql://localhost:3306/bus_station_gfl
    username: springstudent
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
    show-sql: false
  jackson:
    serialization:
      fail-on-empty-beans: false
  swagger-ui:
    path: /swagger-ui.html
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970